
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 45
#define YY_END_OF_BUFFER 46
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[316] =
    {   0,
        0,    0,    0,    0,    0,    0,   46,   44,    9,   10,
       10,    8,   30,   28,   11,   42,   26,   34,   16,   17,
       25,   18,   44,   19,   37,   33,   27,   15,   22,   38,
       38,   38,   35,   12,   38,   38,   38,   38,   38,   38,
       38,   38,   38,   38,   38,   38,   38,   38,   38,   38,
       38,   23,   13,   32,    2,    3,    2,    2,    6,    7,
        6,   10,   29,   14,   42,   43,   42,   42,    0,   35,
        0,    1,    5,    0,   37,    0,   24,   20,   21,   38,
       38,   38,   38,   38,   38,   38,   38,   38,   38,   38,
       38,   38,   35,   38,   38,   38,   38,   38,   38,   38,

       38,   36,   38,   38,   38,   38,   38,   38,   38,   38,
       38,   38,   38,   38,   38,   38,   38,   38,   38,   38,
       38,   38,   38,   31,    3,    4,    7,   42,   40,    0,
        0,   39,   42,   42,   41,    0,   41,    0,   41,   38,
       38,   38,   38,   38,   38,   38,   38,   38,   38,   38,
       38,   38,   38,   38,   38,   38,   38,   38,   35,   38,
       38,   38,   36,   38,   38,   35,   38,   38,   38,   38,
       38,   38,   38,   38,   38,   38,   38,   38,   38,   38,
       38,   38,   38,   38,   38,   38,   38,   38,   38,   38,
       38,   42,   42,   42,   41,   41,   41,   38,   38,   38,

       38,   38,   38,   38,   38,   38,   38,   38,   38,   38,
       38,   38,   38,   38,   38,   38,   38,   38,   38,   38,
       38,   38,   38,   38,   38,   38,   38,   38,   38,   38,
       38,   38,   38,   38,   38,   38,   38,   42,   42,   38,
       38,   38,   38,   38,   38,   38,   38,   38,   35,   38,
       38,   38,   38,   38,   38,   38,   38,   38,   38,   38,
       38,   38,   38,   38,   38,   38,   35,   38,   38,   38,
       38,   42,   38,   38,   38,   38,   38,   38,   38,   38,
       38,   38,   38,   38,   38,   38,   38,   38,   38,   38,
       38,   38,   38,   38,   38,   38,   38,   38,   38,   38,

       38,   38,   38,   38,   38,   38,   38,   38,   38,   38,
       38,   38,   38,   38,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    5,    6,    7,    1,    1,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   19,   19,
       19,   19,   19,   19,   19,   20,   20,    1,   21,   22,
       23,   24,    1,    1,   25,   25,   25,   25,   26,   25,
       25,   25,   27,   25,   25,   25,   25,   25,   25,   25,
       25,   25,   28,   25,   25,   25,   25,   25,   25,   25,
       29,   30,   31,   32,   25,    1,   33,   34,   35,   36,

       37,   38,   39,   40,   41,   25,   42,   43,   44,   45,
       46,   47,   25,   48,   49,   50,   51,   52,   53,   54,
       55,   56,   57,   58,   59,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[60] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    3,    3,
        1,    1,    1,    1,    3,    3,    3,    3,    1,    1,
        1,    1,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    1,    1,    1
    } ;

static const flex_int16_t yy_base[322] =
    {   0,
        0,    0,   57,   59,   61,   63,  350, 1064, 1064, 1064,
      340, 1064,  305, 1064,  281,   72, 1064, 1064, 1064,  270,
     1064,  258,   49,  119,  116, 1064,  248,  236,  224,  119,
      121,  124, 1064, 1064,  126,  128,  132,  136,  142,  148,
      138,  173,  144,  179,  181,  151,  183,  187,  200,  185,
      206, 1064,  183, 1064, 1064, 1064,  229,  195, 1064, 1064,
      207, 1064, 1064, 1064,  124,  170,  139,  185,  230, 1064,
      160, 1064, 1064,  202,  189,  234, 1064, 1064, 1064,    0,
      224,  232,  236,  238,  242,  244,  246,  248,  250,  253,
      257,  259,  269,  273,  276,  284,  286,  288,  290,  292,

      294,  296,  298,  304,  306,  311,  318,  322,  327,  329,
      337,  339,  344,  347,  349,  353,  358,  369,  371,  362,
      378,  373,  382, 1064, 1064, 1064, 1064,  271,  164,  401,
      149,  140,  309,  402,  414,  295,  421,  405, 1064,  419,
      423,  425,  428,  430,  433,  435,  440,  443,  438,  448,
      450,  460,  462,  465,  468,  470,  473,  481,  476,  483,
      488,  491,  493,  496,  498,  501,  503,  505,  507,  513,
      517,  523,  525,  530,  532,  534,  536,  541,  545,  547,
      551,  560,  566,  569,  571,  573,  578,  580,  582,  584,
      586,  325,  538,  597,  600, 1064,  603,  606,  611,  613,

      615,  617,  620,  622,  624,  627,  630,  632,  634,  636,
      638,  647,  649,  656,  662,  666,  671,  673,  675,  679,
      681,  683,  688,  694,  696,  700,  703,  707,  711,  722,
      724,  729,  731,  734,  737,  739,  744,  742,  369,  746,
      749,  751,  754,  766,  771,  768,  776,  778,  781,  783,
      787,  789,  797,  799,  801,  806,  809,  811,  813,  819,
      822,  827,  829,  831,  833,  844,  846,  848,  850,  852,
      855,  461,  857,  863,  865,  871,  874,  880,  882,  887,
      884,  889,  891,  893,  895,  910,  905,  917,  914,  919,
      921,  925,  930,  927,  939,  942,  946,  949,  951,  954,

      959,  965,  968,  961,  970,  972,  974,  976,  983,  987,
      993,  995, 1000, 1002, 1064, 1051, 1054,   72, 1057, 1060,
       68
    } ;

static const flex_int16_t yy_def[322] =
    {   0,
      315,    1,  316,  316,  317,  317,  315,  315,  315,  315,
      315,  315,  315,  315,  315,  315,  315,  315,  315,  315,
      315,  315,  315,  315,  315,  315,  315,  315,  315,  318,
      318,  318,  315,  315,  318,  318,  318,  318,  318,  318,
      318,  318,  318,  318,  318,  318,  318,  318,  318,  318,
      318,  315,  315,  315,  315,  315,  315,  315,  315,  315,
      315,  315,  315,  315,  319,  320,  319,  319,  320,  315,
      315,  315,  315,  315,  315,  315,  315,  315,  315,  321,
      318,  318,  318,  318,  318,  318,  318,  318,  318,  318,
      318,  318,  318,  318,  318,  318,  318,  318,  318,  318,

      318,  318,  318,  318,  318,  318,  318,  318,  318,  318,
      318,  318,  318,  318,  318,  318,  318,  318,  318,  318,
      318,  318,  318,  315,  315,  315,  315,  319,  320,  320,
      320,  320,  319,  319,  315,  315,  315,  315,  315,  318,
      318,  318,  318,  318,  318,  318,  318,  318,  318,  318,
      318,  318,  318,  318,  318,  318,  318,  318,  318,  318,
      318,  318,  318,  318,  318,  318,  318,  318,  318,  318,
      318,  318,  318,  318,  318,  318,  318,  318,  318,  318,
      318,  318,  318,  318,  318,  318,  318,  318,  318,  318,
      318,  319,  319,  319,  315,  315,  315,  318,  318,  318,

      318,  318,  318,  318,  318,  318,  318,  318,  318,  318,
      318,  318,  318,  318,  318,  318,  318,  318,  318,  318,
      318,  318,  318,  318,  318,  318,  318,  318,  318,  318,
      318,  318,  318,  318,  318,  318,  318,  319,  319,  318,
      318,  318,  318,  318,  318,  318,  318,  318,  318,  318,
      318,  318,  318,  318,  318,  318,  318,  318,  318,  318,
      318,  318,  318,  318,  318,  318,  318,  318,  318,  318,
      318,  319,  318,  318,  318,  318,  318,  318,  318,  318,
      318,  318,  318,  318,  318,  318,  318,  318,  318,  318,
      318,  318,  318,  318,  318,  318,  318,  318,  318,  318,

      318,  318,  318,  318,  318,  318,  318,  318,  318,  318,
      318,  318,  318,  318,    0,  315,  315,  315,  315,  315,
      315
    } ;

static const flex_int16_t yy_nxt[1124] =
    {   0,
        8,    9,   10,   11,   12,   13,    8,   14,   15,   16,
       17,   18,   19,   20,   21,   22,   23,   24,   25,   25,
       26,   27,   28,   29,   30,   30,   31,   32,   33,    8,
       33,   34,   35,   36,   37,   38,   39,   40,   41,   30,
       42,   30,   43,   30,   44,   30,   45,   46,   47,   48,
       49,   50,   51,   30,   30,   30,   52,   53,   54,   56,
       57,   56,   57,   60,   61,   60,   61,   71,   71,   58,
       80,   58,   65,   65,   81,   65,   65,   65,   65,   65,
       65,   66,   65,   65,   65,   65,   65,   65,   65,   65,
       67,   67,   65,   65,   65,   65,   68,   68,   68,   68,

       65,   69,   65,   65,   68,   68,   68,   68,   68,   68,
       68,   68,   68,   68,   68,   68,   68,   68,   68,   68,
       68,   68,   68,   68,   68,   68,   68,   68,   65,   65,
       65,   72,   74,  129,   75,   75,   73,   80,   80,   80,
       80,   76,   80,   80,   80,   80,   80,   80,  132,   66,
       80,   80,   76,  130,   80,   80,   80,   80,   66,   84,
       80,   80,   80,   80,   89,   82,   80,   80,  130,   80,
       80,   90,   92,   66,   85,   87,   86,   91,   83,   66,
       97,   93,   88,  101,   94,  135,   95,  111,   98,  105,
       99,   80,   80,  100,  132,   96,  135,   80,   80,   80,

       80,   80,   80,   80,   80,   80,   80,   75,   75,  127,
      102,  106,  126,  109,  130,  107,  103,  104,   80,   80,
      136,  136,  112,  113,   80,   80,  118,  137,  110,  108,
      122,  125,  114,  115,  119,  116,   65,  117,  137,  133,
      124,  120,   80,   80,  121,  123,   79,  138,  134,  138,
       80,   80,  139,  139,   80,   80,   80,   80,   78,   65,
       80,   80,   80,   80,   80,   80,   80,   80,   80,   80,
       77,   80,   80,   70,   65,   80,   80,   80,   80,   65,
       66,  140,  145,   70,  141,  149,  142,   80,   80,   64,
      143,   80,   80,  144,   80,   80,  151,  146,  147,  148,

      130,  150,   80,   80,   80,   80,   80,   80,   80,   80,
       80,   80,   80,   80,   80,   80,   80,   80,  129,  152,
      137,  153,   80,   80,   80,   80,  154,   63,  156,   80,
       80,  137,  157,  155,   66,  158,   80,   80,  130,  159,
       80,   80,   62,  160,  161,   80,   80,   80,   80,  315,
      164,  315,  162,  163,  130,   80,   80,   80,   80,  315,
      165,  168,   80,   80,  167,   80,   80,   80,   80,  169,
      166,   80,   80,  315,  170,  171,   80,   80,  129,  176,
       80,   80,  174,  315,  173,  315,  172,   80,   80,   80,
       80,   80,   80,  179,  177,  178,   80,   80,  130,  175,

       80,   80,  180,  184,  315,  181,  315,  128,  186,  182,
      192,  129,  315,  189,  315,  190,  183,  315,  187,  193,
      194,  185,  191,  139,  139,  166,  188,  195,  315,  195,
      128,  130,  196,  196,  197,  315,  197,   80,   80,  139,
      139,   80,   80,   80,   80,  128,   80,   80,   80,   80,
      128,   80,   80,   80,   80,  198,   80,   80,   80,   80,
      315,   80,   80,  315,  201,  202,   80,   80,   80,   80,
       66,  166,  199,  315,  200,  166,  166,  203,   80,   80,
       80,   80,  206,   80,   80,  102,   80,   80,   80,   80,
      130,   80,   80,  207,   80,   80,  204,  205,  102,   80,

       80,   80,   80,  315,  208,  210,   80,   80,  166,   80,
       80,   80,   80,  211,   80,   80,   80,   80,  209,   80,
       80,   80,   80,   80,   80,   80,   80,  315,  166,  215,
      212,   80,   80,  213,  166,   80,   80,  315,  216,  315,
      214,   80,   80,   80,   80,  166,  217,   66,   80,   80,
       80,   80,   80,   80,   80,   80,  238,  220,  218,   80,
       80,  315,  219,   80,   80,   80,   80,  130,  224,   80,
       80,  315,  222,  221,  223,  315,  226,  228,   80,   80,
      315,  230,  315,  225,   80,   80,  227,   80,   80,   80,
       80,   80,   80,  315,  229,  166,   80,   80,   80,   80,

       80,   80,   80,   80,   80,   80,  129,  166,  166,  233,
      315,  231,  315,  232,  315,  239,  236,  102,  196,  196,
      235,  139,  139,  234,   80,   80,  130,  315,  237,   80,
       80,   80,   80,   80,   80,   80,   80,  315,   80,   80,
       80,   80,   80,   80,  240,   80,   80,  241,   80,   80,
       80,   80,   80,   80,   80,   80,   80,   80,  166,  166,
      242,  315,  243,  315,  244,   80,   80,   80,   80,  315,
      166,  166,  246,  315,   80,   80,  247,  245,  249,  248,
       80,   80,  315,  250,   80,   80,  315,  166,  252,   80,
       80,   80,   80,   80,   80,  315,  251,   80,   80,   80,

       80,   80,   80,  255,  315,  256,   80,   80,  315,  253,
      315,  257,   80,   80,   80,   80,  315,  254,   80,   80,
      315,   80,   80,  315,  260,   80,   80,  258,  259,   80,
       80,  315,  102,  315,  263,  315,  262,  264,  315,  261,
       80,   80,   80,   80,  315,  265,  315,   80,   80,   80,
       80,   66,   80,   80,  166,   80,   80,   80,   80,  315,
      272,  266,   80,   80,   80,   80,  269,   80,   80,   80,
       80,  130,   80,   80,  315,  270,  267,  268,  166,  315,
      102,  315,  273,  274,   80,   80,   80,   80,  271,   80,
       80,  315,  166,  315,   80,   80,   80,   80,  315,   80,

       80,   80,   80,  166,  102,   80,   80,   80,   80,  315,
      275,  277,  315,  276,  315,   80,   80,   80,   80,   80,
       80,  315,  166,  278,   80,   80,  279,   80,   80,   80,
       80,   80,   80,  280,  281,  166,  166,   80,   80,  282,
       80,   80,  315,  284,  315,   80,   80,   80,   80,   80,
       80,   80,   80,  315,  166,  283,  315,  102,  315,  166,
      285,  166,   80,   80,   80,   80,   80,   80,   80,   80,
       80,   80,  166,   80,   80,   80,   80,  315,  286,  315,
      166,   80,   80,   80,   80,  315,  289,  315,  288,   80,
       80,  287,   80,   80,  166,  291,  290,  292,   80,   80,

       80,   80,   80,   80,  166,   80,   80,   80,   80,   80,
       80,   80,   80,   80,   80,  293,  296,  315,  294,  315,
      166,  295,  166,   80,   80,  166,  315,  166,   80,   80,
      315,  298,   80,   80,  166,   80,   80,   80,   80,   80,
       80,  315,  297,   80,   80,   80,   80,  299,   80,   80,
      300,  166,  315,  301,  315,  302,  315,   80,   80,  315,
       80,   80,  315,  303,   80,   80,  166,   80,   80,   80,
       80,  304,   80,   80,  166,  305,  306,   80,   80,   80,
       80,  315,  307,   80,   80,  315,   80,   80,   80,   80,
       80,   80,   80,   80,   80,   80,  166,  166,  308,  315,

      166,   80,   80,  309,  166,   80,   80,  315,  166,  166,
      310,   80,   80,   80,   80,  311,  312,  315,   80,   80,
       80,   80,  315,  315,  315,  315,  315,  315,  315,  315,
      166,  315,  166,  315,  315,  166,  314,  166,  315,  315,
      315,  315,  315,  315,  315,  315,  315,  315,  315,  315,
      313,   55,   55,   55,   59,   59,   59,  128,  315,  128,
      131,  315,  131,    7,  315,  315,  315,  315,  315,  315,
      315,  315,  315,  315,  315,  315,  315,  315,  315,  315,
      315,  315,  315,  315,  315,  315,  315,  315,  315,  315,
      315,  315,  315,  315,  315,  315,  315,  315,  315,  315,

      315,  315,  315,  315,  315,  315,  315,  315,  315,  315,
      315,  315,  315,  315,  315,  315,  315,  315,  315,  315,
      315,  315,  315
    } ;

static const flex_int16_t yy_chk[1124] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    3,
        3,    4,    4,    5,    5,    6,    6,   23,   23,    3,
      321,    4,   16,   16,  318,   16,   16,   16,   16,   16,
       16,   16,   16,   16,   16,   16,   16,   16,   16,   16,
       16,   16,   16,   16,   16,   16,   16,   16,   16,   16,

       16,   16,   16,   16,   16,   16,   16,   16,   16,   16,
       16,   16,   16,   16,   16,   16,   16,   16,   16,   16,
       16,   16,   16,   16,   16,   16,   16,   16,   16,   16,
       16,   24,   25,   65,   25,   25,   24,   30,   30,   31,
       31,   25,   32,   32,   35,   35,   36,   36,   67,  132,
       37,   37,   25,   65,   38,   38,   41,   41,  131,   35,
       39,   39,   43,   43,   37,   31,   40,   40,   67,   46,
       46,   37,   38,  129,   35,   36,   35,   37,   32,   66,
       40,   38,   36,   41,   39,   71,   39,   46,   40,   43,
       40,   42,   42,   40,   68,   39,   71,   44,   44,   45,

       45,   47,   47,   50,   50,   48,   48,   75,   75,   61,
       42,   44,   58,   45,   68,   44,   42,   42,   49,   49,
       74,   74,   47,   47,   51,   51,   48,   74,   45,   44,
       50,   57,   47,   47,   48,   47,   69,   47,   74,   69,
       53,   48,   81,   81,   49,   51,   29,   76,   69,   76,
       82,   82,   76,   76,   83,   83,   84,   84,   28,   69,
       85,   85,   86,   86,   87,   87,   88,   88,   89,   89,
       27,   90,   90,   22,   69,   91,   91,   92,   92,   69,
      128,   82,   87,   20,   83,   90,   84,   93,   93,   15,
       85,   94,   94,   86,   95,   95,   92,   88,   89,   89,

      128,   91,   96,   96,   97,   97,   98,   98,   99,   99,
      100,  100,  101,  101,  102,  102,  103,  103,  133,   93,
      136,   94,  104,  104,  105,  105,   95,   13,   97,  106,
      106,  136,   98,   96,  192,   99,  107,  107,  133,  100,
      108,  108,   11,  101,  103,  109,  109,  110,  110,    7,
      105,    0,  104,  104,  192,  111,  111,  112,  112,    0,
      106,  109,  113,  113,  108,  114,  114,  115,  115,  110,
      107,  116,  116,    0,  110,  111,  117,  117,  239,  114,
      120,  120,  113,    0,  112,    0,  111,  118,  118,  119,
      119,  122,  122,  116,  114,  115,  121,  121,  239,  113,

      123,  123,  117,  119,    0,  118,    0,  130,  120,  118,
      130,  134,    0,  122,    0,  122,  118,    0,  121,  130,
      134,  119,  123,  138,  138,  119,  121,  135,    0,  135,
      130,  134,  135,  135,  137,    0,  137,  140,  140,  137,
      137,  141,  141,  142,  142,  130,  143,  143,  144,  144,
      130,  145,  145,  146,  146,  140,  149,  149,  147,  147,
        0,  148,  148,    0,  143,  145,  150,  150,  151,  151,
      272,  146,  141,    0,  142,  144,  147,  148,  152,  152,
      153,  153,  151,  154,  154,  149,  155,  155,  156,  156,
      272,  157,  157,  152,  159,  159,  150,  150,  153,  158,

      158,  160,  160,    0,  155,  157,  161,  161,  154,  162,
      162,  163,  163,  158,  164,  164,  165,  165,  156,  166,
      166,  167,  167,  168,  168,  169,  169,    0,  160,  163,
      161,  170,  170,  161,  164,  171,  171,    0,  165,    0,
      162,  172,  172,  173,  173,  167,  168,  193,  174,  174,
      175,  175,  176,  176,  177,  177,  193,  171,  169,  178,
      178,    0,  170,  179,  179,  180,  180,  193,  175,  181,
      181,    0,  173,  172,  174,    0,  177,  178,  182,  182,
        0,  180,    0,  176,  183,  183,  177,  184,  184,  185,
      185,  186,  186,    0,  179,  181,  187,  187,  188,  188,

      189,  189,  190,  190,  191,  191,  194,  185,  182,  186,
        0,  183,    0,  184,    0,  194,  190,  189,  195,  195,
      188,  197,  197,  187,  198,  198,  194,    0,  191,  199,
      199,  200,  200,  201,  201,  202,  202,    0,  203,  203,
      204,  204,  205,  205,  198,  206,  206,  199,  207,  207,
      208,  208,  209,  209,  210,  210,  211,  211,  202,  203,
      200,    0,  201,    0,  205,  212,  212,  213,  213,    0,
      209,  204,  207,    0,  214,  214,  208,  206,  210,  208,
      215,  215,    0,  212,  216,  216,    0,  211,  214,  217,
      217,  218,  218,  219,  219,    0,  213,  220,  220,  221,

      221,  222,  222,  217,    0,  218,  223,  223,    0,  215,
        0,  219,  224,  224,  225,  225,    0,  216,  226,  226,
        0,  227,  227,    0,  223,  228,  228,  220,  221,  229,
      229,    0,  222,    0,  226,    0,  225,  227,    0,  224,
      230,  230,  231,  231,    0,  229,    0,  232,  232,  233,
      233,  238,  234,  234,  228,  235,  235,  236,  236,    0,
      238,  230,  237,  237,  240,  240,  233,  241,  241,  242,
      242,  238,  243,  243,    0,  235,  231,  232,  234,    0,
      237,    0,  240,  242,  244,  244,  246,  246,  236,  245,
      245,    0,  241,    0,  247,  247,  248,  248,    0,  249,

      249,  250,  250,  243,  246,  251,  251,  252,  252,    0,
      244,  247,    0,  245,    0,  253,  253,  254,  254,  255,
      255,    0,  248,  249,  256,  256,  250,  257,  257,  258,
      258,  259,  259,  252,  253,  254,  251,  260,  260,  255,
      261,  261,    0,  257,    0,  262,  262,  263,  263,  264,
      264,  265,  265,    0,  260,  256,    0,  259,    0,  261,
      258,  262,  266,  266,  267,  267,  268,  268,  269,  269,
      270,  270,  265,  271,  271,  273,  273,    0,  263,    0,
      264,  274,  274,  275,  275,    0,  269,    0,  268,  276,
      276,  266,  277,  277,  267,  271,  270,  274,  278,  278,

      279,  279,  281,  281,  273,  280,  280,  282,  282,  283,
      283,  284,  284,  285,  285,  275,  281,    0,  279,    0,
      276,  280,  277,  287,  287,  282,    0,  283,  286,  286,
        0,  285,  289,  289,  278,  288,  288,  290,  290,  291,
      291,    0,  284,  292,  292,  294,  294,  286,  293,  293,
      287,  289,    0,  288,    0,  290,    0,  295,  295,    0,
      296,  296,    0,  291,  297,  297,  293,  298,  298,  299,
      299,  294,  300,  300,  292,  295,  296,  301,  301,  304,
      304,    0,  297,  302,  302,    0,  303,  303,  305,  305,
      306,  306,  307,  307,  308,  308,  298,  299,  300,    0,

      302,  309,  309,  301,  303,  310,  310,    0,  306,  307,
      304,  311,  311,  312,  312,  305,  308,    0,  313,  313,
      314,  314,    0,    0,    0,    0,    0,    0,    0,    0,
      311,    0,  309,    0,    0,  310,  313,  314,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
      312,  316,  316,  316,  317,  317,  317,  319,    0,  319,
      320,    0,  320,  315,  315,  315,  315,  315,  315,  315,
      315,  315,  315,  315,  315,  315,  315,  315,  315,  315,
      315,  315,  315,  315,  315,  315,  315,  315,  315,  315,
      315,  315,  315,  315,  315,  315,  315,  315,  315,  315,

      315,  315,  315,  315,  315,  315,  315,  315,  315,  315,
      315,  315,  315,  315,  315,  315,  315,  315,  315,  315,
      315,  315,  315
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "uccompiler2.l"


#line 10 "uccompiler2.l"
    /*Rui Miguel Fonte Ribeiro 2021189478
    Bruno Filipe Almeida 2021237081*/
    #include <stdio.h>
    #include <stdbool.h>
    #include <string.h>
    int line = 1;
    int column = 1;
    int commentLine = 0;
    int commentColumn = 0;
    int commentState= 0;
    bool exist = false;
#line 810 "lex.yy.c"
#line 811 "lex.yy.c"

#define INITIAL 0
#define COMMENT 1
#define SINGLECOMMENT 2

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 22 "uccompiler2.l"


#line 1033 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 316 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1064 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 24 "uccompiler2.l"
{ BEGIN(COMMENT); commentLine = line; commentColumn = column-1; commentState = 1;}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 25 "uccompiler2.l"
{ ; }
	YY_BREAK
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 26 "uccompiler2.l"
{ line+=1; column = 0; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 27 "uccompiler2.l"
{ commentState = 0; BEGIN(INITIAL);}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 29 "uccompiler2.l"
{ BEGIN(SINGLECOMMENT);}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 30 "uccompiler2.l"
{ ; }
	YY_BREAK
case 7:
/* rule 7 can match eol */
YY_RULE_SETUP
#line 31 "uccompiler2.l"
{ line += 1; column = 0; BEGIN(INITIAL);}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 33 "uccompiler2.l"
{ column += 1;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 34 "uccompiler2.l"
{ column += 4;}
	YY_BREAK
case 10:
/* rule 10 can match eol */
YY_RULE_SETUP
#line 35 "uccompiler2.l"
{ line+=1; column = 0;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 37 "uccompiler2.l"
{ if(exist)printf("BITWISEAND\n"); column += 1;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 38 "uccompiler2.l"
{ if(exist)printf("BITWISEXOR\n"); column += 1;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 39 "uccompiler2.l"
{ if(exist)printf("BITWISEOR\n"); column += 1;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 40 "uccompiler2.l"
{ if(exist)printf("AND\n"); column += 2;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 41 "uccompiler2.l"
{ if(exist)printf("ASSIGN\n"); column += 1;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 42 "uccompiler2.l"
{ if(exist)printf("MUL\n"); column += 1;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 43 "uccompiler2.l"
{ if(exist)printf("PLUS\n"); column += 1;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 44 "uccompiler2.l"
{ if(exist)printf("MINUS\n"); column += 1;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 45 "uccompiler2.l"
{ if(exist)printf("DIV\n"); column += 1;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 46 "uccompiler2.l"
{ if(exist)printf("EQ\n"); column += 2;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 47 "uccompiler2.l"
{ if(exist)printf("GE\n"); column += 2;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 48 "uccompiler2.l"
{ if(exist)printf("GT\n"); column += 1;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 49 "uccompiler2.l"
{ if(exist)printf("LBRACE\n");column += 1;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 50 "uccompiler2.l"
{ if(exist)printf("LE\n"); column += 2;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 51 "uccompiler2.l"
{ if(exist)printf("COMMA\n"); column += 1;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 52 "uccompiler2.l"
{ if(exist)printf("LPAR\n"); column += 1;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 53 "uccompiler2.l"
{ if(exist)printf("LT\n"); column += 1;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 54 "uccompiler2.l"
{ if(exist)printf("MOD\n"); column += 1;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 55 "uccompiler2.l"
{ if(exist)printf("NE\n"); column += 2;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 56 "uccompiler2.l"
{ if(exist)printf("NOT\n"); column += 1;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 57 "uccompiler2.l"
{ if(exist)printf("OR\n"); column += 2;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 58 "uccompiler2.l"
{ if(exist)printf("RBRACE\n"); column += 1;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 59 "uccompiler2.l"
{ if(exist)printf("SEMI\n"); column += 1;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 60 "uccompiler2.l"
{ if(exist)printf("RPAR\n"); column += 1;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 63 "uccompiler2.l"
{ if(exist)printf("RESERVED(%s)\n", yytext); column += yyleng; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 64 "uccompiler2.l"
{ if(exist)for(int i = 0; i < yyleng;i++) printf("%c",yytext[i]-32);printf("\n"); column += yyleng;}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 65 "uccompiler2.l"
{ if(exist)printf("NATURAL(%s)\n", yytext); column += yyleng;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 66 "uccompiler2.l"
{ if(exist)printf("IDENTIFIER(%s)\n", yytext); column+= yyleng;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 67 "uccompiler2.l"
{ if(exist)printf("CHRLIT(%s)\n", yytext); column+= yyleng; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 68 "uccompiler2.l"
{ if(exist)printf("CHRLIT(%s)\n", yytext); column+= yyleng; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 69 "uccompiler2.l"
{ if(exist)printf("DECIMAL(%s)\n", yytext); column += yyleng;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 70 "uccompiler2.l"
{ if(exist)printf("Line %d, column %d: unterminated char constant\n",line,column);column += yyleng;}              
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 71 "uccompiler2.l"
{ if(exist)printf("Line %d, column %d: invalid char constant (%s)\n",line,column,yytext);column += yyleng;}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 73 "uccompiler2.l"
{ printf("Line %d, column %d: unrecognized character (%s)\n",line,column,yytext); column += yyleng;} 
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 75 "uccompiler2.l"
ECHO;
	YY_BREAK
#line 1318 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(COMMENT):
case YY_STATE_EOF(SINGLECOMMENT):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 316 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 316 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 315);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 75 "uccompiler2.l"

extern int yylex();
int main(int argc, char *argv[]) {
    if(argv[1] != NULL && strcmp(argv[1],"-l") == 0){ exist = true;}
    exist = true;
    yylex();    /* run the lexical analysis automaton */
    return 0;
}
int yywrap() {  /* called on EOF, return 1 to terminate */
    if(commentState == 1){ printf("Line %d, column %d: unterminated comment\n",commentLine,commentColumn); }
    return 1;
}
