
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 76
#define YY_END_OF_BUFFER 77
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[279] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   77,   75,   74,   73,   75,   19,   46,   17,
       75,   14,   23,    5,    8,    2,    7,   75,    6,   43,
       43,    1,   16,    4,   11,   45,   15,   24,    3,   45,
       45,   45,   45,   45,   45,   45,   45,   45,   45,   45,
       45,   45,   45,   12,   75,   22,   56,   53,   52,   56,
       56,   49,   48,   49,   49,   51,   50,   51,   76,   62,
       76,   65,   66,   59,   58,   59,   59,   61,   60,   61,
       72,   68,   72,   67,   71,   73,   18,   20,   41,   44,

       39,   40,   44,   43,   42,    0,    0,   43,   13,    9,
       10,   45,   45,   45,   45,   45,   45,   45,   45,   45,
       45,   45,   45,   45,   41,   29,   45,   45,   45,   45,
       45,   45,   45,   45,   45,   45,   45,   45,   21,   52,
       54,   55,   48,   47,   50,   62,   65,   65,    0,   63,
       65,   58,   57,   60,   68,   70,   69,    0,   44,   42,
        0,   44,   43,   45,   45,   45,   45,   45,   45,   45,
       45,   45,   45,   28,   45,   45,   45,   31,   41,    0,
       45,   45,   45,   45,   45,   45,   45,   30,   65,   65,
        0,    0,   65,    0,   44,   33,   45,   45,   45,   45,

       45,   27,   45,   45,    0,   37,   45,   45,    0,   45,
       45,   45,   45,   45,   45,   45,   45,   65,   64,   65,
        0,    0,   65,   45,   45,   45,   45,    0,   45,   45,
        0,   45,   45,   45,   45,   45,   45,   45,   65,   65,
       63,   65,   45,   45,   45,   45,    0,   45,    0,   45,
       26,   45,   34,   64,   65,   45,   45,   32,    0,   45,
       38,   25,   45,   65,   45,    0,   45,    0,   45,    0,
        0,   45,    0,    0,   35,    0,   36,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    5,    6,    7,    1,    1,    8,    9,    1,   10,
       11,   12,   13,   14,   15,   16,   17,   18,   19,   20,
       21,   19,   19,   19,   19,   22,   22,    1,   23,   24,
       25,   26,    1,    1,   27,   28,   28,   28,   29,   28,
       30,   30,   30,   30,   30,   30,   30,   30,   30,   31,
       30,   30,   30,   30,   30,   30,   30,   32,   30,   30,
       33,   34,   35,    1,   36,    1,   37,   38,   39,   40,

       41,   42,   43,   44,   45,   30,   46,   47,   48,   49,
       50,   51,   30,   52,   53,   54,   55,   56,   57,   32,
       58,   30,   59,   60,   61,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[62] =
    {   0,
        1,    1,    2,    2,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    3,    3,    3,
        3,    3,    1,    1,    1,    1,    3,    3,    3,    4,
        4,    4,    1,    1,    1,    4,    3,    3,    3,    3,
        3,    3,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    1,    1,
        1
    } ;

static const flex_int16_t yy_base[298] =
    {   0,
        0,    0,   60,   64,   67,   70,   72,   80,   82,   84,
      529,  528,    0,    0,   89,   91,   93,   95,  101,  103,
        0,    0,  534,  537,  537,  537,  530,  507,  537,  537,
      522,  537,  537,  537,  517,  537,  514,   93,  104,  104,
      122,  537,  503,  502,  501,    0,  537,  537,    0,   28,
      102,  484,  477,  110,  473,  106,  485,  468,  483,   90,
      112,  461,  481,  537,  457,  537,  537,  537,  537,  513,
      117,  537,  537,  512,  497,  537,  537,  510,  537,  537,
      509,  164,  537,  537,  537,  508,  493,  537,  537,  506,
      537,  537,  505,  537,  142,  537,  537,  537,  537,  159,

      537,  537,  183,  197,  211,  224,    0,  235,  537,  537,
      537,    0,  457,  465,  452,  467,  454,  460,  448,  453,
      449,  444,  427,  426,  409,    0,  375,  370,  372,  405,
      381,  370,  364,  370,  364,  369,  362,  360,  537,  537,
      537,  537,  537,  537,  537,  537,  186,  537,  408,  537,
      255,  537,  537,  537,  537,  537,  537,  248,  253,  292,
      188,  259,    0,  363,  372,  367,  357,   64,   91,  364,
      356,  364,  384,    0,  359,  347,  346,  354,    0,  367,
      347,  347,  334,  347,  117,  333,  345,    0,  281,  378,
      167,  152,  283,  280,  308,    0,  337,  328,  336,  323,

      323,    0,  319,  313,  332,    0,  310,  304,  303,  309,
      299,  287,  299,  286,  285,  292,  279,  288,  537,  316,
      309,  317,  338,  257,  258,  259,  275,  241,  229,  223,
      217,  207,  200,  194,  198,  198,  182,  191,  340,  345,
      537,  350,  179,  174,  173,  203,  177,  184,  158,  158,
        0,  141,    0,  180,  373,  154,  142,    0,  136,  144,
      537,    0,  166,  357,  120,  119,  123,  134,  107,   83,
       65,   65,   53,   50,  537,   45,  537,  537,  427,  431,
      435,  439,  443,  447,  451,  453,  457,  461,   69,  465,
      469,  473,  477,  481,  485,  489,  493

    } ;

static const flex_int16_t yy_def[298] =
    {   0,
      278,    1,  279,  279,  280,  280,  281,  281,  282,  282,
      282,  282,  282,  282,  283,  283,  284,  284,  285,  285,
      282,  282,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  286,  278,  278,  286,  286,
      286,  286,  286,  286,  286,  286,  286,  286,  286,  286,
      286,  286,  286,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  287,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  288,  278,  278,  278,  278,  278,

      278,  278,  278,  278,  278,  278,  289,  278,  278,  278,
      278,  286,  286,  286,  286,  286,  286,  286,  286,  286,
      286,  286,  286,  286,  286,  286,  286,  286,  286,  286,
      286,  286,  286,  286,  286,  286,  286,  286,  278,  278,
      278,  278,  278,  278,  278,  278,  287,  278,  278,  278,
      290,  278,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  289,  286,  286,  286,  286,  286,  286,  286,
      286,  286,  286,  286,  286,  286,  286,  286,  286,  278,
      286,  286,  286,  286,  286,  286,  286,  286,  291,  292,
      292,  293,  294,  278,  278,  286,  286,  286,  286,  286,

      286,  286,  286,  286,  278,  286,  286,  286,  278,  286,
      286,  286,  286,  286,  286,  286,  286,  291,  278,  295,
      292,  278,  296,  286,  286,  286,  286,  278,  286,  286,
      278,  286,  286,  286,  286,  286,  286,  286,  291,  296,
      278,  295,  286,  286,  286,  286,  278,  286,  278,  286,
      286,  286,  286,  293,  297,  286,  286,  286,  278,  286,
      278,  286,  286,  296,  286,  278,  286,  278,  286,  278,
      278,  286,  278,  278,  278,  278,  278,    0,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  278

    } ;

static const flex_int16_t yy_nxt[599] =
    {   0,
       24,   25,   26,   27,   25,   28,   29,   30,   31,   32,
       33,   34,   35,   36,   37,   38,   39,   40,   41,   41,
       41,   41,   42,   43,   44,   45,   46,   46,   46,   46,
       46,   46,   47,   24,   48,   49,   46,   50,   51,   52,
       53,   54,   55,   46,   56,   46,   46,   57,   46,   58,
       59,   60,   61,   62,   46,   63,   46,   46,   64,   65,
       66,   68,   69,   70,   68,   68,   69,   70,   68,   73,
       74,  163,   73,   74,   77,   78,   71,  113,   75,  114,
       71,   75,   77,   78,   80,   81,   80,   81,   82,  277,
       82,   85,   86,   85,   86,   89,   90,   89,   90,  276,

       87,  275,   87,   92,   93,   92,   93,   94,  179,   94,
      100,  100,  100,  100,  100,  101,  198,  199,  274,  103,
      102,  104,  104,  104,  104,  105,  132,  200,  141,  273,
      133,  201,  106,  142,   95,  107,   95,  103,  115,  108,
      108,  108,  108,  108,  106,  116,  120,  126,  157,  272,
      106,  117,  134,  127,  128,  214,  121,  122,  150,  123,
      271,  215,  106,  179,  124,  135,  148,  149,  136,  148,
      150,  216,  270,  219,  269,  157,  100,  100,  100,  100,
      100,  268,  267,  157,  266,  222,  150,  158,  148,  149,
      157,  265,  150,  157,  179,  157,  263,  151,  262,  158,

      159,  159,  159,  159,  159,  162,  162,  162,  162,  162,
      261,  158,  103,  222,  104,  104,  104,  104,  105,  151,
      260,  259,  258,  158,  257,  106,  103,  179,  160,  160,
      160,  160,  105,  256,  179,  179,  161,  106,  161,  106,
      253,  162,  162,  162,  162,  162,  252,  179,  251,  250,
      103,  106,  108,  108,  108,  108,  108,  190,  191,  249,
      194,  192,  194,  106,  248,  195,  195,  195,  195,  195,
      159,  159,  159,  159,  159,  106,  162,  162,  162,  162,
      162,  158,  179,  148,  149,  190,  191,  219,  193,  150,
      148,  149,  247,  158,  219,  246,  147,  195,  195,  195,

      195,  195,  245,  147,  244,  243,  147,  103,  147,  160,
      160,  160,  160,  105,  220,  219,  151,  238,  190,  191,
      106,  220,  219,  192,  147,  195,  195,  195,  195,  195,
      237,  147,  106,  236,  147,  235,  147,  234,  233,  179,
      148,  149,  148,  149,  241,  232,  219,  148,  149,  220,
      192,  241,  190,  191,  231,  230,  254,  218,  192,  148,
      149,  229,  228,  241,  218,  192,  227,  218,  192,  218,
      192,  242,  226,  220,  179,  190,  191,  225,  242,  241,
      224,  179,  179,  255,  219,  179,  217,  213,  212,  211,
      242,  240,  210,  209,  208,  207,  179,  206,  240,  205,

      204,  240,  203,  240,  202,  179,  242,  179,  197,  196,
      148,  188,  187,  186,  240,  185,  184,  183,  182,  181,
      180,  240,  179,  178,  240,  177,  240,   67,   67,   67,
       67,   72,   72,   72,   72,   76,   76,   76,   76,   79,
       79,   79,   79,   84,   84,   84,   84,   88,   88,   88,
       88,   91,   91,   91,   91,  112,  112,  147,  147,  147,
      147,  156,  176,  156,  156,  189,  189,  189,  189,  218,
      218,  218,  218,  221,  175,  221,  221,  192,  174,  192,
      192,  223,  223,  223,  223,  239,  239,  239,  239,  240,
      240,  240,  240,  264,  264,  264,  264,  173,  172,  171,

      170,  169,  168,  167,  166,  165,  164,  155,  154,  153,
      152,  146,  145,  144,  143,  140,  139,  138,  137,  131,
      130,  129,  125,  119,  118,  111,  110,  109,   99,   99,
       98,   97,   96,  278,   83,   83,   23,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  278

    } ;

static const flex_int16_t yy_chk[599] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    3,    3,    3,    3,    4,    4,    4,    4,    5,
        5,  289,    6,    6,    7,    7,    3,   50,    5,   50,
        4,    6,    8,    8,    9,    9,   10,   10,    9,  276,
       10,   15,   15,   16,   16,   17,   17,   18,   18,  274,

       15,  273,   16,   19,   19,   20,   20,   19,  272,   20,
       38,   38,   38,   38,   38,   39,  168,  168,  271,   40,
       39,   40,   40,   40,   40,   40,   60,  169,   71,  270,
       60,  169,   40,   71,   19,   40,   20,   41,   51,   41,
       41,   41,   41,   41,   40,   51,   54,   56,   95,  269,
       41,   51,   61,   56,   56,  185,   54,   54,  192,   54,
      268,  185,   41,  267,   54,   61,   82,   82,   61,  191,
       82,  185,  266,  191,  265,   95,  100,  100,  100,  100,
      100,  263,  260,   95,  259,  192,  254,  100,  147,  147,
       95,  257,  147,   95,  256,   95,  252,   82,  250,  100,

      103,  103,  103,  103,  103,  161,  161,  161,  161,  161,
      249,  103,  104,  254,  104,  104,  104,  104,  104,  147,
      248,  247,  246,  103,  245,  104,  105,  244,  105,  105,
      105,  105,  105,  243,  238,  237,  106,  104,  106,  105,
      236,  106,  106,  106,  106,  106,  235,  234,  233,  232,
      108,  105,  108,  108,  108,  108,  108,  151,  151,  231,
      158,  151,  158,  108,  230,  158,  158,  158,  158,  158,
      159,  159,  159,  159,  159,  108,  162,  162,  162,  162,
      162,  159,  229,  189,  189,  193,  193,  189,  151,  193,
      218,  218,  228,  159,  218,  227,  151,  194,  194,  194,

      194,  194,  226,  151,  225,  224,  151,  160,  151,  160,
      160,  160,  160,  160,  189,  221,  193,  217,  220,  220,
      160,  218,  220,  222,  193,  195,  195,  195,  195,  195,
      216,  193,  160,  215,  193,  214,  193,  213,  212,  211,
      223,  223,  239,  239,  223,  210,  239,  240,  240,  220,
      222,  240,  242,  242,  209,  208,  242,  220,  222,  264,
      264,  207,  205,  264,  220,  222,  204,  220,  222,  220,
      222,  223,  203,  239,  201,  255,  255,  200,  240,  255,
      199,  198,  197,  242,  190,  187,  186,  184,  183,  182,
      264,  242,  181,  180,  178,  177,  176,  175,  242,  173,

      172,  242,  171,  242,  170,  167,  255,  166,  165,  164,
      149,  138,  137,  136,  255,  135,  134,  133,  132,  131,
      130,  255,  129,  128,  255,  127,  255,  279,  279,  279,
      279,  280,  280,  280,  280,  281,  281,  281,  281,  282,
      282,  282,  282,  283,  283,  283,  283,  284,  284,  284,
      284,  285,  285,  285,  285,  286,  286,  287,  287,  287,
      287,  288,  125,  288,  288,  290,  290,  290,  290,  291,
      291,  291,  291,  292,  124,  292,  292,  293,  123,  293,
      293,  294,  294,  294,  294,  295,  295,  295,  295,  296,
      296,  296,  296,  297,  297,  297,  297,  122,  121,  120,

      119,  118,  117,  116,  115,  114,  113,   93,   90,   87,
       86,   81,   78,   75,   74,   70,   65,   63,   62,   59,
       58,   57,   55,   53,   52,   45,   44,   43,   37,   35,
       31,   28,   27,   23,   12,   11,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  278

    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "gocompiler.l"
#line 2 "gocompiler.l"
    /*
    Projeto de Compiladores 2023/2024~
    Meta 2
    2021189478 - Rui Ribeiro
    2021221169 - Francisco Rodrigues
    */
    //gocompiler_v4 teste de substituicao dos comments - resultado correu bem apenas 0 erros agora - corrigido tirar i_semi dos comentarios
    
    #include "y.tab.h"
    #include "ast.h"
    #include <stdio.h>
    #include <stdlib.h>
    #include <string.h>
    #include <stdbool.h>
    int yyparse(void);
    extern struct node *program;
    int line = 1;
    int comment_lines = 1; 
    int col = 0;
    int comment_cols = 0;
    int flag_1, swaped_line;
    int i_semicolon = 0;
    int start_brace = 0;
    #define PASS_TOKEN() yylval.token = strdup(yytext); 
#line 695 "lex.yy.c"

#line 697 "lex.yy.c"

#define INITIAL 0
#define SEMICOLON 1
#define BCOMMENT 2
#define LCOMMENT 3
#define STRING 4
#define DUMMY_QUOTE 5
#define OCTAL 6
#define SEMIBCOMMENT 7
#define SEMILCOMMENT 8
#define INVALID_STRING 9
#define SEMICOLON2 10

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 42 "gocompiler.l"


#line 927 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 279 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 537 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 44 "gocompiler.l"
{if (flag_1) if(i_semicolon==0){fprintf(yyout, "SEMICOLON\n");}if(i_semicolon==1){fprintf(yyout, "SEMICOLON\n");i_semicolon=0;} col+=yyleng; yylval.value = (char*) strdup(yytext); return SEMICOLON;}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 45 "gocompiler.l"
{if (flag_1) fprintf(yyout, "COMMA\n"); col+=yyleng; i_semicolon=0; yylval.value = (char*) strdup(yytext); return COMMA;}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 46 "gocompiler.l"
{if (flag_1) fprintf(yyout, "BLANKID\n"); col+=yyleng; i_semicolon=0; yylval.value = (char*) strdup(yytext); return BLANKID;}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 47 "gocompiler.l"
{if (flag_1) fprintf(yyout, "ASSIGN\n"); col+=yyleng; i_semicolon=0; yylval.value = (char*) strdup(yytext); return ASSIGN;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 48 "gocompiler.l"
{if (flag_1) fprintf(yyout, "STAR\n"); col+=yyleng; i_semicolon=0; yylval.value = (char*) strdup(yytext); return STAR;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 49 "gocompiler.l"
{if (flag_1) fprintf(yyout, "DIV\n"); col+=yyleng; i_semicolon=0; yylval.value = (char*) strdup(yytext); return DIV;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 50 "gocompiler.l"
{if (flag_1) fprintf(yyout, "MINUS\n"); col+=yyleng; i_semicolon=0; yylval.value = (char*) strdup(yytext); return MINUS;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 51 "gocompiler.l"
{if (flag_1) fprintf(yyout, "PLUS\n"); col+=yyleng; i_semicolon=0; yylval.value = (char*) strdup(yytext); return PLUS;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 52 "gocompiler.l"
{if (flag_1) fprintf(yyout, "EQ\n"); col+=yyleng; i_semicolon=0; yylval.value = (char*) strdup(yytext); return EQ;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 53 "gocompiler.l"
{if (flag_1) fprintf(yyout, "GE\n"); col+=yyleng; i_semicolon=0; yylval.value = (char*) strdup(yytext); return GE;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 54 "gocompiler.l"
{if (flag_1) fprintf(yyout, "GT\n"); col+=yyleng; i_semicolon=0; yylval.value = (char*) strdup(yytext); return GT;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 55 "gocompiler.l"
{if (flag_1) fprintf(yyout, "LBRACE\n"); start_brace = 1; col+=yyleng;i_semicolon=0; yylval.value = (char*) strdup(yytext); return LBRACE;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 56 "gocompiler.l"
{if (flag_1) fprintf(yyout, "LE\n"); col+=yyleng; i_semicolon=0; yylval.value = (char*) strdup(yytext); return LE;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 57 "gocompiler.l"
{if (flag_1) fprintf(yyout, "LPAR\n"); col+=yyleng; i_semicolon=0; yylval.value = (char*) strdup(yytext); return LPAR;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 58 "gocompiler.l"
{if (flag_1) fprintf(yyout, "LSQ\n"); col+=yyleng; i_semicolon=0; yylval.value = (char*) strdup(yytext); return LSQ;}	
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 59 "gocompiler.l"
{if (flag_1) fprintf(yyout, "LT\n"); col+=yyleng; i_semicolon=0; yylval.value = (char*) strdup(yytext); return LT;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 60 "gocompiler.l"
{if (flag_1) fprintf(yyout, "MOD\n"); col+=yyleng; i_semicolon=0; yylval.value = (char*) strdup(yytext); return MOD;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 61 "gocompiler.l"
{if (flag_1) fprintf(yyout, "NE\n"); col+=yyleng; i_semicolon=0; yylval.value = (char*) strdup(yytext); return NE;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 62 "gocompiler.l"
{if (flag_1) fprintf(yyout, "NOT\n"); col+=yyleng; i_semicolon=0; yylval.value = (char*) strdup(yytext); return NOT;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 63 "gocompiler.l"
{if (flag_1) fprintf(yyout, "AND\n"); col+=yyleng; i_semicolon=0; yylval.value = (char*) strdup(yytext); return AND;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 64 "gocompiler.l"
{if (flag_1) fprintf(yyout, "OR\n"); col+=yyleng; i_semicolon=0; yylval.value = (char*) strdup(yytext); return OR;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 65 "gocompiler.l"
{if (flag_1) fprintf(yyout, "RBRACE\n"); col+=yyleng; i_semicolon=1; yylval.value = (char*) strdup(yytext); return RBRACE;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 66 "gocompiler.l"
{if (flag_1) fprintf(yyout, "RPAR\n"); col+=yyleng; i_semicolon=1; yylval.value = (char*) strdup(yytext); return RPAR;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 67 "gocompiler.l"
{if (flag_1) fprintf(yyout, "RSQ\n"); col+=yyleng; i_semicolon=1; yylval.value = (char*) strdup(yytext); return RSQ;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 68 "gocompiler.l"
{if (flag_1) fprintf(yyout, "PACKAGE\n"); col+=yyleng; i_semicolon=0; yylval.value = (char*) strdup(yytext); return PACKAGE;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 69 "gocompiler.l"
{if (flag_1) fprintf(yyout, "RETURN\n"); col+=yyleng; i_semicolon=1; yylval.value = (char*) strdup(yytext); return RETURN;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 70 "gocompiler.l"
{if (flag_1) fprintf(yyout, "ELSE\n"); col+=yyleng; i_semicolon=0; yylval.value = (char*) strdup(yytext); return ELSE;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 71 "gocompiler.l"
{if (flag_1) fprintf(yyout, "FOR\n"); col+=yyleng; i_semicolon=0; yylval.value = (char*) strdup(yytext); return FOR;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 72 "gocompiler.l"
{if (flag_1) fprintf(yyout, "IF\n"); col+=yyleng; i_semicolon=0; yylval.value = (char*) strdup(yytext); return IF;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 73 "gocompiler.l"
{if (flag_1) fprintf(yyout, "VAR\n"); col+=yyleng; i_semicolon=0; yylval.value = (char*) strdup(yytext); return VAR;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 74 "gocompiler.l"
{if (flag_1) fprintf(yyout, "INT\n"); col+=yyleng; i_semicolon=0; yylval.value = (char*) strdup(yytext); return INT;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 75 "gocompiler.l"
{if (flag_1) fprintf(yyout, "FLOAT32\n"); col+=yyleng; i_semicolon=0; yylval.value = (char*) strdup(yytext); return FLOAT32;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 76 "gocompiler.l"
{if (flag_1) fprintf(yyout, "BOOL\n"); col+=yyleng; i_semicolon=0; yylval.value = (char*) strdup(yytext); return BOOL;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 77 "gocompiler.l"
{if (flag_1) fprintf(yyout, "STRING\n"); col+=yyleng; i_semicolon=0; yylval.value = (char*) strdup(yytext); return STRING;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 78 "gocompiler.l"
{if (flag_1) fprintf(yyout, "PRINT\n"); col+=yyleng; i_semicolon=0; yylval.value = (char*) strdup(yytext); return PRINT;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 79 "gocompiler.l"
{if (flag_1) fprintf(yyout, "PARSEINT\n"); col+=yyleng; i_semicolon=0; yylval.value = (char*) strdup(yytext); return PARSEINT;}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 80 "gocompiler.l"
{if (flag_1) fprintf(yyout, "FUNC\n"); col+=yyleng; i_semicolon=0; yylval.value = (char*) strdup(yytext); return FUNC;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 81 "gocompiler.l"
{if (flag_1) fprintf(yyout, "CMDARGS\n"); col+=yyleng; i_semicolon=0; yylval.value = (char*) strdup(yytext); return CMDARGS;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 82 "gocompiler.l"
{col++; comment_lines = 0; comment_cols = 0; swaped_line = 0; BEGIN BCOMMENT;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 83 "gocompiler.l"
{col++; BEGIN LCOMMENT;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 85 "gocompiler.l"
{if (flag_1) fprintf(yyout, "RESERVED(%s)\n", yytext); col+=yyleng; i_semicolon=0;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 86 "gocompiler.l"
{if (flag_1) fprintf(yyout, "Line %d, column %d: invalid octal constant (%s)\n",line,++col, yytext); col+=yyleng-1; }    // NATURAL: Constantes octais (começa com 0, seguido por dígitos de 0 a 7)
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 87 "gocompiler.l"
{if (flag_1) fprintf(yyout, "NATURAL(%s)\n", yytext); col+=yyleng; yylval.value = (char*) strdup(yytext); i_semicolon=1; }    // NATURAL: Todos os naturais
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 88 "gocompiler.l"
{if (flag_1) fprintf(yyout, "DECIMAL(%s)\n", yytext); col+=yyleng; yylval.value = (char*) strdup(yytext); i_semicolon=1;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 89 "gocompiler.l"
{if (flag_1) fprintf(yyout, "IDENTIFIER(%s)\n", yytext); col+=yyleng; yylval.value = (char*) strdup(yytext); i_semicolon=1;}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 90 "gocompiler.l"
{yyless(0); BEGIN STRING;}  
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 93 "gocompiler.l"
{line+=comment_lines; if (swaped_line) col = 0; else col++; col+=comment_cols+yyleng; BEGIN 0;}
	YY_BREAK
case 48:
/* rule 48 can match eol */
YY_RULE_SETUP
#line 94 "gocompiler.l"
{comment_lines++; comment_cols = 0; swaped_line = 1;}
	YY_BREAK
case YY_STATE_EOF(BCOMMENT):
#line 95 "gocompiler.l"
{fprintf(yyout, "Line %d, column %d: unterminated comment\n", line, col); yyterminate();}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 96 "gocompiler.l"
{comment_cols+=yyleng;}
	YY_BREAK
case 50:
/* rule 50 can match eol */
YY_RULE_SETUP
#line 98 "gocompiler.l"
{if(flag_1 && i_semicolon==1) fprintf(yyout, "SEMICOLON\n");i_semicolon=0;line++; col = 0; BEGIN 0;}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 99 "gocompiler.l"
{;}
	YY_BREAK
case 52:
/* rule 52 can match eol */
YY_RULE_SETUP
#line 101 "gocompiler.l"
{if (flag_1) fprintf(yyout, "SEMICOLON\n");line++; col = 0; BEGIN 0;}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 102 "gocompiler.l"
{col+=yyleng;}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 103 "gocompiler.l"
{col++; comment_lines = 0; comment_cols = 0; swaped_line = 0; BEGIN SEMIBCOMMENT;}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 104 "gocompiler.l"
{BEGIN SEMILCOMMENT;}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 105 "gocompiler.l"
{yyless(0); BEGIN 0;}
	YY_BREAK
case YY_STATE_EOF(SEMICOLON):
#line 106 "gocompiler.l"
{if (flag_1) fprintf(yyout, "SEMICOLON\n"); yyterminate();}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 110 "gocompiler.l"
{line+=comment_lines; if (swaped_line) col = 0; else col++; col+=comment_cols+yyleng; if (swaped_line) {fprintf(yyout, "SEMICOLON\n"); BEGIN 0;} else BEGIN SEMICOLON;}
	YY_BREAK
case 58:
/* rule 58 can match eol */
YY_RULE_SETUP
#line 111 "gocompiler.l"
{comment_lines++; comment_cols = 0; swaped_line=1; }
	YY_BREAK
case YY_STATE_EOF(SEMIBCOMMENT):
#line 112 "gocompiler.l"
{fprintf(yyout, "SEMICOLON\n"); fprintf(yyout, "Line %d, column %d: unterminated comment\n", line, col); yyterminate();}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 113 "gocompiler.l"
{comment_cols+=yyleng;}
	YY_BREAK
case 60:
/* rule 60 can match eol */
YY_RULE_SETUP
#line 115 "gocompiler.l"
{yyless(0); BEGIN SEMICOLON;}
	YY_BREAK
case YY_STATE_EOF(SEMILCOMMENT):
#line 116 "gocompiler.l"
{fprintf(yyout, "SEMICOLON\n"); yyterminate();}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 117 "gocompiler.l"
{;}
	YY_BREAK
case 62:
/* rule 62 can match eol */
YY_RULE_SETUP
#line 119 "gocompiler.l"
{fprintf(yyout, "Line %d, column %d: unterminated string literal\n", line, col); line++; col = 0; BEGIN 0;}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 120 "gocompiler.l"
{if (flag_1) fprintf(yyout, "STRLIT(%s)\n", yytext); col+=yyleng; BEGIN SEMICOLON;}
	YY_BREAK
case 64:
/* rule 64 can match eol */
YY_RULE_SETUP
#line 121 "gocompiler.l"
{yyless(0); BEGIN DUMMY_QUOTE;}
	YY_BREAK
case 65:
/* rule 65 can match eol */
YY_RULE_SETUP
#line 122 "gocompiler.l"
{yyless(0); BEGIN DUMMY_QUOTE;}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 125 "gocompiler.l"
{col++; comment_cols = 1; BEGIN INVALID_STRING;}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 126 "gocompiler.l"
{col+=comment_cols; BEGIN 0;}
	YY_BREAK
case 68:
/* rule 68 can match eol */
YY_RULE_SETUP
#line 127 "gocompiler.l"
{fprintf(yyout, "Line %d, column %d: unterminated string literal\n", line, col); line++; col = 0; BEGIN 0;}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 128 "gocompiler.l"
{comment_cols+=yyleng;}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 129 "gocompiler.l"
{fprintf(yyout, "Line %d, column %d: invalid escape sequence (%s)\n", line, col+comment_cols, yytext); comment_cols+=yyleng;}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 130 "gocompiler.l"
{fprintf(yyout, "Line %d, column %d: invalid escape sequence (%s)\n", line, col+comment_cols, yytext); comment_cols+=yyleng;}
	YY_BREAK
case YY_STATE_EOF(INVALID_STRING):
#line 131 "gocompiler.l"
{fprintf(yyout, "Line %d, column %d: unterminated string literal\n", line, col); yyterminate();}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 132 "gocompiler.l"
{comment_cols+=yyleng;}
	YY_BREAK
case 73:
/* rule 73 can match eol */
YY_RULE_SETUP
#line 135 "gocompiler.l"
{line++; col = 0;if(i_semicolon == 1 && start_brace == 0)fprintf(yyout, "SEMICOLON\n"); yylval.value = (char*) strdup(yytext); i_semicolon=0;start_brace=0;BEGIN 0;}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 136 "gocompiler.l"
{col+=yyleng;}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 137 "gocompiler.l"
{col+=1; fprintf(yyout, "Line %d, column %d: illegal character (%s)\n", line, col, yytext);col+=yyleng-1;int next_char = input();if (next_char != EOF) {unput(next_char);}}
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(LCOMMENT):
case YY_STATE_EOF(STRING):
case YY_STATE_EOF(DUMMY_QUOTE):
case YY_STATE_EOF(OCTAL):
case YY_STATE_EOF(SEMICOLON2):
#line 139 "gocompiler.l"
{ if (i_semicolon == 1) if (flag_1) fprintf(yyout, "SEMICOLON\n");return 0;}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 140 "gocompiler.l"
ECHO;
	YY_BREAK
#line 1403 "lex.yy.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 279 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 279 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 278);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 140 "gocompiler.l"


int main(int argc, char *argv[]){
    if (argv[1] != 0 && (argv[1][0] == '-' && argv[1][1] == 'l')){
        //checkig for argument -l like this so we dont have to import string.h
        flag_1 = 1;
        yylex();
    } 
    if (argv[1] != 0 && (argv[1][0] == '-' && argv[1][1] == 't')){
        flag_1 = 1;
        yyparse();
    }  
    //print_ast(program);

    /*if (flag_1 == 1){
        yylex();
    }
    return 0;*/

    //free_ast(program);
}

int yywrap(){
    return 1;
}
